- mkdocs.yml
This was missed in https://github.com/uktrade/data-workspace/pull/3, bringing in the public facing documentation for Data Workspace
> ci: move in mkdocs.yml to deploy docs

- README.md
This tidies up the README, and focuses it more on sending people to the right repository that they might be interested in.
> docs: list of repositories that make up Data Workspace

- README.md
When referring to the repository (as opposed to the actual application), let's try using the lower-case and hyphenated form for consistency. That's the GitHub default.
> docs: use lowercase and hyphenated data-workspace

- README.md
This is so it's not stretched and appears as designed
> docs: use the correct dimensions on logo

- README.md
This puts PostgreSQL up front and center. While there are some components of Data Workspace that would be useful without PostgreSQL, it's certainly the focus/core.
> docs: make it clear this is PostgreSQL-based

- docs/index.md
Realise that the link to GitHub should probably be right there on the page
> docs: link to GitHub more prominently

- README.md
The word "core" was used in multiple ways in the README in terms of repositories. Suspect this was confusing.
> docs: avoid using the word 'core' in multiple ways

- docs/development/maintenance-mode.md
All the other pages from what I can tell don't use title case
> docs: avoid title case on the maintenance page

- docs/404.md
This adds a custom 404 page, which replaces GitHub Pages default. It's now very similar to
https://github.com/x-govuk/govuk-eleventy-plugin/blob/main/docs/404.md, which is itself similar to gov.uk's 404 page.
> docs: add 404 page

- eleventy.config.js
Makes the footer just a touch more useful I think, and maybe gives a bit of an air of a more "finished" site.
> docs: add link to sitemap in the footer

- infra/ecs_main_admin.tf
Heavy load on the datasets db can slow down responses from the /healthcheck endpoint. This in turn can cause ECS to start some replacement tasks and casus data workspace to start flapping.
Until we can resolve this in a nicer way, set the timeout to 30 seconds.
> feat: set admin load balancer healthcheck timeout to 30 seconds

- infra/ecs_main_superset.tf
- infra/security_groups.tf
This makes recent Superset deployable by increasing the timeout for its load balance health check, and also opens up the Sentry proxy to allow exceptions to be sent to it.
> fix: make recent Superset deployable

- infra/ecs_notebooks_jupyterlab_python.tf
- infra/ecs_notebooks_notebook.tf
- infra/ecs_notebooks_notebook_container_definitions.json
- infra/ecs_notebooks_remote_desktop.tf
- infra/ecs_notebooks_superset.tf
- infra/ecs_notebooks_theia.tf
- infra/ecs_pgadmin.tf
- infra/ecs_rstudio.tf
- infra/ecs_rstudio_rv4.tf
- infra/main.tf
This adds the permission for each user to log S3Sync metrics to Cloudwatch, specifically ones added in https://github.com/uktrade/mobius3/releases/tag/v0.0.42
It also tightens up permissions on the Cloudwatch VPC endpoints, making sure that only our AWS accounts can use them.
> feat: allow logging of S3Sync/mobius3 metrics to CloudWatch

- docs/deployment/frontend.md
This change updates the docs around tagging and releasing the frontend application.
> Update documentation around tag formatting

- infra/main.tf
- infra/rds_datasets.tf
This adds the option datasets_rds_cluster_instance_monitoring_interval that allows the configuration of enhanced monitoring on the RDS datasets database.
The default 0, means it's disabled, which is existing behaviour.
> feat: allow optional enhanced monitoring on the datasets database

- infra/ecs_main_mlflow.tf
We _almost_ supported multiple MLFlow instance before. However, there was one spot that only supported one. Now, we _really_ support multiple MLFlow instances.
> feat: support multiple MLFlow

- package-lock.json
- package.json
Increase docs-building dependencies, and simplifies package.json, because I don't think the optional dependency is needed any more.
Inspired by `npm ci` taking many hours in other projects with a similar package.json. It didn't here, but doing this bump/tidy for consistency.
> build(deps): bump docs-building dependencies

- infra/security_groups.tf
The security group that allowed connection from the admin application to the MLFlow load balancer had the hard coded formula for only the first load balancer's IP address. This now correctly uses the right IP address for each load balancer.
> fix: connection to MLFlow load balancer from admin application

- infra/ecs_main_gitlab.tf
add theia to aws iam policy for gitlab runner, as it contains conda and it can used as base image
> add theia to aws iam policy for gitlab runner

- infra/ecs_notebooks_notebook.tf
This adds support to the VPC endpoint configuration for a second MLFlow instance to access its bucket.
It's not great that the number is hard coded to 2 - others parts of the Terraform support 0 or more. However, leaving that tidy up to further work since it was already hard coded (to 1), and so not a meaningful step backwards.
> feat: support for a second MLFlow to store artefacts in a bucket

- infra/ecs_notebooks_notebook.tf
This continues (or maybe, fixes?) the change from
f8368806c87f2763705528829538988dc31c8ffc and makes the number of MLFlow instance not as hard coded as it was - any number, 0 or more, should be now supported.
> fix: support any number of MLFlow instances in bucket config

- infra/main.tf
- infra/mwaa.tf
Initial basic setup of MWAA.
We are currently just aiming to get a single pipeline ingesting data into Data Workspace, and in order to do that we need things fired up in the correct VPCs/subnets etc, with access to at least one bucket, and will also down the line need some credentials. So we're Terraform-ing early on in the process to not build up a debt to have to do it later, and to find out if we can do everything we do need to do via Terraform
> feat: initial Amazon Managed Workflows for Apache Airflow (MWAA) 

- infra/mwaa.tf
- infra/security_groups.tf
Continuing on the work to add MWAA to Data Workspace, this allows the datasets DB to accept incomming PostgreSQL connections from MWAA, and allows MWAA to take secrets from AWS Secrets Manager.
At this point MWAA _can_ ingest data into Data Workspace.
> feat: MWAA can communicate with datasets db, and access secrets

- infra/vpc.tf
We don't know of any particular thing in the datasets VPC that allows users to make DNS queries, especially to unauthorised servers, so this is a defense in depth/just in case change. We are soon to put ArrangoDB in the dame VPC, so I think it makes sense to tighten things down as we increase the surface area otherwise.
It is set to only allow queries to amazonaws.com domains, and block everything else. While we might be able to block it further in future, this is a step forward in terms of locking things down.
In the notebooks VPC we have a similar setup, but with what is essentially our own custom firewall, written before the Route53 Firewall existed. If this goes well, potentially we could shut that down in favour of this for the notebooks VPC.
> feat: filter DNS queries from the datasets VPC using the Route53 Firewall

- infra/main.tf
It was a bit of an oversight that they're not - the terraform itself can handle them being the empty string, in which case it won't make the Airflow resources.
> feat: make Airflow variables optional

- infra/ecr.tf
- infra/ecs_main_airflow.tf
- infra/ecs_main_airflow_container_definitions.json
- infra/main.tf
- infra/mwaa.tf
- infra/route_53.tf
- infra/security_groups.tf
This is a basic ECS Airflow set up, comparing it to the MWAA Airflow set up.
GOV.UK PaaS is shutting down, so we need to move off. MWAA Airflow doesn't give us the ability to run DAGs without access to all other DAGs' credentials, so we are investigating how straight forward it is to do that with our own Airflow on ECS.
> feat: ECS Airflow 

- infra/ecr.tf
- infra/ecs_main_airflow.tf
- infra/ecs_main_airflow_dag_processor_container_definitions.json
- infra/main.tf
- infra/security_groups.tf
Infra work for detaching DAG processors from the ECS Airflow scheduler. Each DAG processor is now a standalone ECS service, allowing for scalability based on the number of teams. This change enables a clear separation of environments, aligning with the principles outlined in AIP-43: DAG Processor separation (https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-43+DAG+Processor+separation).
> feat: ecs airflow team-based dag processors

- infra/airflow_dag_tasks.tf
- infra/airflow_dag_tasks_container_definitions.json
We always override the cpu and memory from the DAG tasks, it is easier if they
are not specified here to avoid any conflictions and errors.
> Remove memory and cpu from airflow DAG tasks

- infra/airflow_dag_processor.tf
- infra/airflow_scheduler.tf
- infra/airflow_scheduler_container_definitions.json
- infra/airflow_webserver.tf
Our (slightly) custom ECS executor for Airflow will run tasks using a different role for each team. The arn of the roles will follow a pattern - a prefix followed by the folder that the dag of the Airflow task is in.
This change makes that prefix available to the Airflow scheduler that runs the executor, so the executor can then choose the correct role to run each task under.
> feat: per-team role arn prefix available to Airflow scheduler

- infra/airflow_dag_processor.tf
Gives the airflow teams permission to access their relevant secret in AWS Secrets Manager
> Give the airflow teams permission to access their relevant secret in AWS Secrets Manager

- infra/airflow_dag_processor.tf
- infra/airflow_dag_processor_container_definitions.json
This passes the name of the Secrets Manager secret for each team, so the team-specific code can fetch it (and convert it to environment variables for DAG code).
> feat: Airflow teams know the name of the team secret

- infra/airflow_scheduler.tf
- infra/airflow_scheduler_container_definitions.json
This passes the prefix (i.e. the environment name) to the the scheduler, so it can in turn work out the secret ID to pass to tasks, so they can retrieve the secret with their team's environment variables in
> feat: Airflow scheduler knows the prefix so it can pass the right team secret ID to dags

- infra/airflow_webserver_container_definitions.json
Whilst investigating a potential webserver issues, noticed that we were "name" secret key instead of Airflow Webserver Secret Key.
> feat:Changing the secret key to airflow webserver secret key

- infra/airflow_scheduler.tf
- infra/airflow_scheduler_container_definitions.json
- infra/security_groups.tf
- infra/vpc.tf
Currently scheduler and webserver share the same secuirty groups, meaning load server can connect to the scheduler when it should not be able to.
Therefore, we are spliting the security groups, one for scheduler and one for webserver.
This introduces a concept that we haven't used so far: "prefix lists" on a VPC endpoint. This means the scheduler doesn't need to talk to the world in order to pull its docker images from S3, and can just communicate with S3.
We should probably tighten up the permissions on the S3 endpoint, but leaving that to another change (because this change doesn't allow anything that wasn't previously allowed).
This also contains a change to allow the scheduler to create log groups, which seems to be required for it to create tasks. Although it's unknown why this …
> feat: tightening security groups between scheduler and webserver

- infra/security_groups.tf
With the adition of the private ECS endpoint, tools were not starting up because the ECS endpoint was not open to requests from the admin service.
> fix: tool startup

- infra/ecr.tf
- infra/ecs_main_admin.tf
- infra/ecs_main_admin_container_definitions.json
- infra/ecs_main_arango.tf
- infra/ecs_main_arango_container_definitions.json
- infra/ecs_main_arango_user_data.sh
- infra/environment-template/main.tf
- infra/main.tf
- infra/route_53.tf
- infra/security_groups.tf
- infra/vpc.tf
(Optionally) adds Arango to Data Workspace
Includes Arango ECS service connecting to the main ECS cluster.
ArangoDB instance run using EC2 to allow for Elastic Block Storage to attach to ArangoDB instances when spun up (auto-scaling group). There is a load balancer to connect the Data workspace tools to the ArangoDB instance.
The EBS volume mounts to /data directory within the instance, and the ArangoDB container task definition mounts the instance's /data directory to /var/lib/arangodb3 directory within the container (as this is where data is stored in an Arango database).
As the Arango EC2 instance is in a private subnet and the Datasets VPC does not have access to the internet, VPC Endpoints were used too allow the EC2 insrtance to connect to ECS. The endpoints were placed in the …
> feat: add ArangoDB

- infra/airflow_dag_processor_container_definitions.json
- infra/airflow_dag_tasks_container_definitions.json
Removes environment variables that are currently exported from terraform that will be exported from AWS secrets manager during GOV.UK PaaS migration
> Remove Datasets DB creds and Sentry DSN from terraform for airflow containers

- infra/airflow_s3.tf
- infra/main.tf
This creates a bucket per team for Airflow pipelines, the so-called legacy pipelines that ingest into S3. This is part of the project of moving our Airflow instance out of GOV.UK PaaS which is shutting down, doing essentially a lift and shift into Data Workspace proper.
At the moment getting credentials for the bucket to the team code is slightly faffy using Terraform's "output" and then copy/pasting them into secrets manager, but it's the easiest way for now. Using roles would be "better" but would require a bit of a code change in data-flow, so leaving that to further work so we don't get blocked on it and can still migrate pipelines
>  feat: buckets for so-called legacy Airflow pipelines

- infra/airflow_webserver.tf
- infra/airflow_webserver_container_definitions.json
This does 2 things:
- It stops the Airflow webserver from attempting to connect to GitHub on startup. It shouldn't need to do this because the dag-processors and tasks themselves pull from GitHub.
- Uses a "service registry" to allow Airflow to be communcated with from inside Data Workspace without going via the public internet, and specifically under the DNS name "airflow.jupyterhub". This is to support Data Workspace's so-called derived/SQL pipelines to talk to Airflow without going over the public internet.
> feat: Airflow webserver connectability

- infra/security_groups.tf
The Airflow webserver listens on port 8080, so we have to open that up.
> feat: Data Workspace to the new Airflow

- infra/airflow_webserver.tf
- infra/airflow_webserver_container_definitions.json
- infra/main.tf
We've configured Airflow to accept incoming requests from Data Workspace for some cases of creating DAGs dynamically. These need credentials on the Airflow side.
> feat: credentials for Airflow to accept dynamic/derived/SQL pipeline requests

- infra/security_groups.tf
This is to tasks can talk to the ECS API, since we have some pipelines that fire up ECS tasks
> Adding in a dag processor security group rule

- infra/security_groups.tf
This PR updates the security rules for the Airflow dag processor to allow egress on TCP from any port to the internet (as well as removing any rules that have become redundant as a result of this udpate)
This is to allow pipelines to more readily communicate with the internet for data ingest, without having to update security rules every time
> Allow egress from airflow dag processor services on tcp to all ports

- infra/ecs_main_admin_container_definitions.json
This PR specifies that the protocl for communicating with ArangoDB in non-local environments should be HTTPS rather than HTTP
> Add https as ArangoDB connection protocol env var

- infra/ecs_main_admin.tf
This PR uses the departmental domain name for connections to the ArangoDB load balancer, to resolve the issue with the certificate being presented only being valid for the departmental domain name
> Point admin container at departmental domain name for ArangoDB load balancer

- infra/ecs_main_arango.tf
This adds the AWS environment name prefix (dev-, staging- etc.) to the name of the IAM policy for the ArangoDB EBS, avoiding errors due to resources having the same name
> Prefix the name of the ArangoDB EBS IAM policy with the AWS environment name

- infra/vpc.tf
This PR sets the count for the number of subnets and route table associations for the datasets db to be more appropriately aligned with the datasets subnets AZs variable
> Set count of subnets resources for datasets db on correct AZs variable

- infra/airflow_webserver.tf
This is maybe a bit odd, but it helps certain VPNs route requests appropriately, especially in the case of Airflow being on the subdomain of Data Workspace, which has a wildcard TLS certificate and can cause problems when users flip between Airflow and the rest of Data Workspace (and specifically browsers re-using the connection of one for another).
This also meant moving to a network load balancer, since application load balancers apparently don't support fixed IP addresses.
> feat: put the Airflow webserver on a fixed public IP address

- infra/vpc.tf
We're seeing suspiciously high costs of the main Nat Gatway. We are now running our data pipelines through it, so some increase is to be expected, but it seems still a bit too high.
Reviewing our infrastructure made us realise that the S3 VPC endpoint, although it exists, is not attached to the route table, and so was unused. This means that for some of our S3-intensive pipelines, such as the pipelines that mirror large repositories and push then to S3, the data is going through the Nat Gateway _twice_: once to pull the data into memory in tasks, and then again when getting pushed to S3.
This won't help reduce costs of data on the way in, but hopefully it should eliminate all the costs from pushing data to S3.
> fix: S3 endpoint in main VPC

- infra/ecs_main_arango.tf
- infra/ecs_main_arango_container_definitions.json
- infra/main.tf
This does 2 things
- Increases the healthcheck timeout for Arango - it looked like during normal usage it would take longer than the default (5 seconds?) and cause the instance to deregister
- Makes the memory allocated to Arango customisable, using the current as the default
> feat: increase Arango healthcheck timeout and customisable memory

- infra/ecs_main_arango.tf
Some queries were taking longer than the default of 1 minutes
> feat: increase Arango timeout to 10 minutes

- infra/main.tf
- infra/rds_admin.tf
* enable max allocated rds storage (autoscaling), running out of storage brings down prod and is a terraform-only fix (can't change storage on console once max storage is reached)
> feat: flexible admin rds storage

- infra/ecs_notebooks_notebook_container_definitions.json
As a step towards consistency between tools, now also mounting the tools home directory at /home/dw-user as well as /home/<tool-specific-name>.
Once deployed and all tools user /home/dw-user should be able to remove the /home/<tool-specific-name>
> feat: mount home directory in tools in /home/dw-user

- infra/ecs_main_mirrors_sync.tf
For consistency with the other tools-y images so we can always push to master
> feat: use master for cran binary task

- infra/airflow_dag_processor.tf
This gives Airflow teams access to a "_2" secret.
This is to work around the limitation that an AWS Secret has a max size of 64KB
> feat: allow multiple secrets for Airflow teams

- infra/s3_mirrors.tf
This PR adds a disabled lifecycle rule that would move objects in the mirror bucket > 128KB into the S3 intelligent tier, which once enabled should save money
> Enable intelligent tiering on mirror bucket for objects > 128KB

- infra/ecr.tf
Because we only used tagged images in ECS, to reduce costs and to avoid alerts for vulnrabilities that have since been addressed, we should be able to safely delete untagged images.
The exception are the various visualisation-base images which we do (for now) use untagged, although this is being changed.
> feat: add lifecycle policies to all ECR repos, except visualisation-base images

- infra/ecs_main_gitlab.tf
This change allows ddat data science gitlab runner to list and put objects to their space in notebooks bucket for private python index.
List is needed to check what whl files are available in the package folder and create appropriate index html from gitlab CI pipeline. And Put is to push this html as well as the python build files.
> security policy change for private python index for ddat data science

- infra/ecs_main_gitlab.tf
incorrectly removed gitlab_runner user_provided actions instead of removing them from gitlab_runner_data_science, this PR corrects it
> correct gitlab_runner user_provided actions

- infra/ecr.tf
This adds to the lifecycle rules for preview visualisation (user provided) images. It should now expire preview images one day after they have been pushed.
In order to leave production images alone robustly, they now have a "--prod" suffix so they will match the rule with pattern "*--prod" that expires them in 1000 years. While odd, it seems to be the best way to make "*--prod" images _never_ expire.
> feat: expire preview visualisation (user provided) images

- infra/ecs_main_gitlab.tf
correct iam role name for gitlab data science runner
> rename iam role for gitlab data science runner

- infra/ecs_main_gitlab.tf
we need to create an index html at the root of package, for that it needs to list all available whl files and create the html. So it needs relevant permissions.
> add list object permissions to check for whl files in each package

- infra/s3_notebooks.tf
We have no need to keep the old delete markers, and apparently there is a performance benefit.
> perf: delete expired object delete markers on notebooks bucket

- infra/ecr.tf
- infra/ecs_main_gitlab.tf
We've now moved all visualisation-base images to a single ECR repo, and also use tagged images, so we
- Remove the language-specific visualisaiton base repos
- And give the remaining repo a lifecycle policy to cleanup old images, both for cost reasons and to save us being alerted on vulnrabilities on old images.
> feat: move to single visualisation-base ECR repo, with lifecycle policy

- infra/ecr.tf
This fixes the issue where "python" and "rv4" images were being expired from the visualisation-base repository.
I incorrectly thought that if an image matches any of the patterns in the tag_pattern_list in a rule, it would match the rule and stop processing. However, it has to match _all_ of the patterns.
So to fix the issue, the one rule that matches "python","rv4" is split into two rules.
> fix: visualisation-base lifecycle rule

- infra/ecs_main_gitlab.tf
- infra/ecs_main_gitlab_container_definitions.json
Instead of having to have files local in the filesystem (which is tricky to store securely), that are then copied to S3, which GitLab pulls from on launch, this makes it so GitLab secrets are stored in Secrets Manager, which GitLab pulls from on launch.
This is a part 1 of (probably) 2 parts - this does not remove existing object, permissions or any associated config, to allow environments to keep on accessing the secrets as they were, so we don't have to migrate them all at once. Later parts will likely remove permissions and config.
This is part of our move away from having to have any secrets locally on the filesystem.
> feat: move GitLab secrets to secrets manager (part 1)

- infra/s3_gitlab.tf
This follows up from https://github.com/uktrade/data-workspace/pull/223 by making it possible to apply the terraform with GitLab enabled, but while not have GitLab secrets on the local filesystem.
> feat: move GitLab secrets to secrets manager (part 2)

- infra/environment-template/main.tf
This PR is a part of an overall migration task, to migrate GitLab infrastructure project to GitHub. This particular instance is to use admin_environment secrets from AWS secrets manager instead of local file.
> using admin_environment secrets from aws secrets manager instead of file

- infra/main.tf
- infra/s3_mirrors.tf
The mirror bucket has essentially two modes:
- As a "resource", which is used for the live/production environment
- As a "data source", which is used for non-prod environments, and refers to the one in the production account (to not have to duplicate the bucket - it's big, and only contains public code)
However, before this change the non-prod environment had to be in the same AWS account as the prod one... which is a bit odd in many setups. Now the non-prod environments can be in another AWS account, but still use the mirror bucket from the prod one.
> feat: make it possible for other AWS accounts to use the mirror bucket

- .github/workflows/deploy-docs-to-github-pages.yml
This is done by upgrading to more recent versions of the actions involved in deploying
> ci: fix GitHub pages deployment of docs

- infra/ecs_notebooks_notebook.tf
Remove user permissions to access the central SageMaker S3 bucket from Theia/Jupyter.  This is no longer needed as outputs are copied from the SageMaker S3 bucket into the user's own filespace.  I have tested this change by:
- Verifying that it is still possible to access a user's own SageMaker outputs from the user's own file area
- Verifying that it is not possible to access the SageMaker S3 bucket from Theia
> fix: remove user perms to access SageMaker S3 bucket

- infra/sagemaker_llm_resources.tf
Remove (by commenting out) gemma and llama endpoints.  These are not currently required.
NB: perhaps we should consider deleting these modules altogether.
> fix: remove gemma and llama endpoints

- infra/modules/sagemaker_deployment/cloudwatch.tf
- infra/modules/sagemaker_deployment/lambda.tf
- infra/modules/sagemaker_deployment/main.tf
- infra/modules/sagemaker_deployment/outputs.tf
- infra/modules/sagemaker_deployment/sns.tf
- infra/modules/sagemaker_deployment/variables.tf
To make the changes I'm implementing for composite alarms easier, I propose to refactor the sagemaker_deployment module by splitting it into multiple files. In this first MR I implement that split with no functional changes - so this terraform applies exactly to feat/sagemaker-llms. Merging this first should then make it easier to follow the changes in my second MR to follow where the functional changes will be.
Please see here for guidance on resource naming conventions:
https://developer.hashicorp.com/terraform/language/style#resource-naming
> refactor no functional changes

- infra/ecr.tf
- infra/ecs_matchbox_matchbox.tf
- infra/ecs_matchbox_matchbox_container_definitions.json
- infra/main.tf
- infra/security_groups.tf
- infra/vpc.tf
Infrastructure for running matchbox https://github.com/uktrade/matchbox in data-workspace. This contains:
- A Matchbox VPC.
- A Matchbox Postgres instance.
- A Fargate task for the Matchbox API.
- An s3 bucket for caching parquet files uploaded to the API.
- DNS resolution for the API endpoint.
- Security groups allowing traffic from tools containers. 
- Basic Cloudwatch logging. 
Additionally this PR contains a matchbox_dev_mode_on flag for features which assist with development of Matchbox. These are not intended to be included in the final Matchbox infrastructure and will be removed in a future PR:
- Security groups allowing traffic from tools containers directly to the MatchboxDB database. 
- An additional s3 bucket for storing development artefacts.
> feat: add matchbox infrastructure

- infra/sagemaker.tf
* Deactivating the code to move logs to S3 buckets
* Retaining the module functionality as it may be revived in future to help us get user data associated with the log (perhaps?) which can be used for log retrieval for ensuring we get latest logs specific to user-accounts
> Deactivating

- infra/ecs_main_gitlab.tf
This PR adds visualisation base image access to data science gitlab runner security policy
For the GitLab runner to be able to build packages
> give visualisation base image access to data science gitlab runner

- infra/ecs_notebooks_notebook.tf
removing IAM policy that is granting permissions for sagemaker endpoints
removing IAM policy that is grantinc permissions for VPC endpoints
these permissions were on the task exection role which is assumed by ECS infra and ECS ifra doesn't make sagemaker calls
> remove redundant sagemaker policies

- infra/ecs_notebooks_notebook.tf
- infra/vpc.tf
Recent changes incorrectly used specific resources in SageMaker actions in an attempt to restrict access from tools to other AWS Accounts.
However, various SageMaker actions only support "*" as the resource, so access has to be restricted using another mechanism - for example using a ConditionKey on the Principal. This is what this change does.
It also slightly opens up the policy on the SageMaker VPC Endpoint to allow all actions. This is done to keep the terraform/policy code minimal, and doesn't actually increase what users(via their AWS role) can do, because they still have an identity-based policy that restricts that.
> fix: restore SageMaker access without access to other accounts

- infra/ecs_notebooks_notebook.tf
from notebook_s3_access_template policy, to restrict tools from doing anything on vpcs
> remove vpc endpoint access for sagemaker

- infra/ecs_notebooks_notebook.tf
These buckets are used by SageMaker itself, not from users in tools, and so there shouldn't need to be any access granted.
> refactor: remove jumpstart-* bucket access from notebooks VPC endpoint

- infra/security_groups.tf
Removing SageMaker ingress and egress security group rules because they are not needed.
> remove SageMaker security group rules

- infra/sagemaker.tf
- infra/vpc.tf
This removes the peering connection between the SageMaker VPC and the Main VPC (we thought we did this earlier, but only removed some routes), removes some unnecessary security group rules, and tightens the rule between the SageMaker endpoints in the Notebooks VPC and the main VPC.
> refactor: remove unused SageMaker security group rules and peering

- infra/sagemaker.tf
- infra/sagemaker_llm_resources.tf
- infra/security_groups.tf
- infra/vpc.tf
- Makes sure that the models have one security group, and the VPC endpoints relating to SageMaker have another, so they can be controlled separately.
- Tightens the allowed port for sagemaker to communicate with endpoints to just 443, and only to endpoints
- Removes unnecessary egress on the endpoint security group, since endpoints as far as I know do not initiate connections, which is what egress allows
> security: tighten SageMaker security groups

- infra/sagemaker.tf
This makes it really clear what component needs to talk to the SageMaker endpoints - the notebooks (i.e. tools), an dmean if we ever put anything else in the notebooks VPC, it won't be able to to inadvertantly communicate with the SageMaker endpoints.
(We maybe could do with doing similar things in other rules)
> refactor: refer to security group rather then VPC CIDR in rule

- infra/vpc.tf
This adds internet access to the matchbox VPC - done in order for it to be able to send metrics/logs to Datadog.
This is done using the standard public/private subnet pattern: adding a public subnet with an NAT instance that routes to the internet via an internet gateway.
> feat: add internet gateway to matchbox vpc

- infra/security_groups.tf
This restricts the egress from matchbox to DataDog (+ things like VPC endpoints, the security group rules for which are already in place)
This is to restrict what the code in matchbox can do (e.g. if it's compromised)
> security: limit matchbox egress to Datadog

- infra/ecs_matchbox_matchbox_container_definitions.json
Speculative improvements to matchbox datadog config:
- Removing DD_HOST since I think the agent can detect this fine
- Enabling DD_APM_NON_LOCAL_TRAFFIC since that is apparently needed for multi-container environments
To try to get more data into Datadog from Matchbox
> feat: improve matchbox datadog config

- infra/main.tf
- infra/sagemaker_llm_resources.tf
Updates as required for sagemaker https://uktrade.atlassian.net/browse/TF-235?atlOrigin=eyJpIjoiMDIzMGU4Y2FiZTMyNDk1ODljYmJiNDg5MTM0NzYxYjgiLCJwIjoiaiJ9
Because the variables that set the uptime of the LLMs on each invoke are set in data-workspace repo, they can’t be varied by environment. There is an interest to vary these so that instead of 60mins uptime as set in dev-a then the production environment should be 15mins. The way this can be achieved is to set within data-workspace code that these are externally set variables, and then set the values within data-workspace-deploy instead. Then can be 60mins in dev-a and 15mins in prod. This MR resolves this by abstracting this.
> TF-235: Increasing uptime of LLMs and abstracting

- infra/ecs_matchbox_matchbox.tf
- infra/ecs_matchbox_matchbox_container_definitions.json
- infra/main.tf
We are adding basic API Key authentication to write endpoints for the Matchbox API container. This PR adds the API Key to the Matchbox API container as an environment variable. 
To reduce write endpoint access to a more limited set of users.
> API Key variable added to matchbox container

- infra/ecs_matchbox_matchbox.tf
- infra/ecs_matchbox_matchbox_container_definitions.json
Added missing "p" to "mb_api_ai_key" in "infra/ecs_matchbox…_matchbox.tf" and "infra/ecs_matchbox_matchbox_container_definitions.json"
> refactor: added missing "p" to "mb_api_ai_key"

- infra/ecs_main_admin.tf
- infra/ecs_main_admin_container_definitions.json
This is the infrastructure side of https://github.com/uktrade/data-workspace-frontend/pull/3522, populating an environment variable in tools.
This is so the Matchbox client library can more easily communicate with Matchbox.
> feat: add Matchbox client API root variable to tools

- .github/workflows/lint-terraform-python.yml
This upgrade Ubuntu in GitHub actions for the linting job
This is because the older version is under brownout and will be completely removed soon.
> ci: upgrade Ubuntu in linting

- infra/ecs_matchbox_codebuild.tf
- infra/main.tf
This adds the ability for Matchbox's CodeBuild project to be triggered from GitHub merge or release, configurable per environment.
It does require the "CodeConnection" to GitHub to be setup manually for the account Matchbox is deployed to. As far as I can tell, there is no way around this being a manual step.
This should allow the team to deploy Matchbox more easily in a more CD way
> feat: Matchbox CodeBuild triggerable from GitHub merge or releases

- infra/ecr.tf
This PR updates the policies for the VPC endpoint that permits the use of both DKR and AWS APIs, such that any actions are permitted on this endpoint, provided they originate from within the same AWS account
This avoids the need to update the endpoints policies every time we make a relevant change. No role/user in Data Workspace will be able to do more than they were allowed to before as a result of this change, given their identity-based policies applied to them.
It also more strongly enforces the rule that this endpoint should not be used by other AWS accounts
> Update policy for ECR and DKR endpoints to permit all actions within same AWS account

- infra/security_groups.tf
This fixes the Matchbox codebuild project - we missed a security group rule.
To get Matchbox deployable
> fix: Matchbox codebuild

- infra/main.tf
- infra/vscode_codebuild.tf
Set 'codebuild_compute_type' to 'SMALL' for all tools but set it to 'MEDIUM' for theia to fix codebuild project from failing due to running out of memory.
Created a security group rule to allow codebuild build builds to initiate connections on port '13371' which allows apt-key to work, which is part of R Studio's build.
Links to give more detail or background, e.g. a ticket in JIRA or Trello, a release or commit in another repository. But all text above should be standalone: don't assume the reader can or will access any external links.
e.g.
See: [Description](https://example.com/)
--->
> fix: codebuild compute types and apt-key port

- infra/security_groups.tf
- infra/vscode_codebuild.tf
This PR adds sidecar containers S3Sync and metrics to build with CodeBuild
Moving away from Jenkins
> adding S3Sync, metrics sidecar container images to build with CodeBuild

- infra/ecs_matchbox_matchbox.tf
- infra/environment-template/main.tf
- infra/main.tf
Adding a subscription filter to pass cloudwatch logs to datadog.
This is done via firehose datastream, which was setup manually. This datastream
is at account level and can be used across all cloudwatch groups.
> adding a subscription filter to pass cloudwatch logs to datadog

- infra/0102-providers.tf
- infra/main.tf
Move Providers to 0102-providers from main.tf
We are attempting to tidy up the structure of the data workspace terraform to follow the agreed format laid out in [this confluence page](https://uktrade.atlassian.net/wiki/spaces/DE/pages/4702437398/Data+Workspace+Terraform+Plan).
[Relevant Fb Pitch
](https://trello.com/c/SuoCrhZw/632-speed-security-and-reusability-tidy-the-data-workspace-terraform)
> refactor: moving providers from main to 0102-providers

- infra/ecs_matchbox_matchbox.tf
This fixes applying Terraform when matchbox is on with dev mode
Without this, it is impossible to fully apply the Terraform in some environments.
> fix: applying Terraform when matchbox on without dev mode

- infra/0204-core--route53.tf
- infra/route_53.tf
This moves the data block that fetches the main Route53 zone into core.
This is part of the ongoing work to tidy up the Terraform
> refactor: move data element of Route53 zone to core

- infra/0202-core--vpc-endpoints.tf
- infra/0401-datasets--vpc.tf
This moves the ECS endpoint definition to the "core" section
This is done because the ECS endpoint is on the main vpc, which is defined in "core"
> refactor: move VPC endpoint to more appropriate file

- infra/0701-datasets--vpc.tf
- infra/0702-datasets-postgresql--rds.tf
- infra/security_groups.tf
- infra/vpc.tf
This removes the now-unused VPC peering connection (and assocaited resources) used when Airflow was running in GOV.UK PaaS and need to communicate.
This is to keep the Terraform and infrastructure tidy
> infra: remove unused VPC peering with GOV.UK PaaS

- infra/1202-quicksight--sg.tf
This removes an unnecessary QuickSight security group rule, that theoretically would allow the datasets database to initiate connections to QuickSight. I strongly suspect this is already impossible/would acheive nothing already.
It also adds a comment to explain why there is an unusual security group rule remaining that would not typically be needed for a client -> server connection.
This is done to be as secure as possible - standard minimisation of privilege/swiss-cheese type of change. For the avoidance of doubt, I strongly suspect even without this change it is already impossible for the database to initial such a connection, certainly for a user to initiate such a connection, and also impossible if such a connection were possible to use the connection for anything.
> security: remove unnecessary QuickSight security group rule

- infra/security_groups.tf
This adds a big comment to the top of security_groups.tf explaining that it should not be used.
This is to encourage a better structure in future
> docs: explain that the security_groups.tf file is legacy

- infra/0702-datasets-postgresql--rds.tf
- infra/0906-tools--ecs.tf
- infra/1501-sagemaker.tf
- infra/modules/security_group_client_server_connections/main.tf
- infra/security_groups.tf
This adds a module for security group rules, and also makes the tools/notebooks tasks use them.
This is done to:
1. Reduce verbosity of the security group rules. And specifically the module
- Avoids having to manually create both ingress and egress rules on both sides
- Avoids having to specific the protocol, which is almost always tcp
- Allows creation of rules "in bulk", e.g. if a client has to talk to multiple servers.
2. Avoid confusion about what ports in what direction need to be opened. Security groups are stateful and allow data _back_ through a connection (with the exception of QuickSight's security group which is different), but this is often forgotten
3. Make it really clear what tools/notebooks can connect to. All definition of
the security group rules are in one place, and …
> refactor: module for security group rules

- infra/0702-datasets-postgresql--rds.tf
- infra/1104-superset--ecs.tf
- infra/security_groups.tf
This moves the Superset security group rules to its client side, and uses our internal module to define them.
This is in keeping with what is now the convention
> refactor: move Superset security group rules to client side

- infra/0916-tools-sentry-proxy--ecs.tf
- infra/1010-gitlab--ecr.tf
- infra/1503-sagemaker--vpc-endpoints.tf
- infra/1504-sagemaker--deployments.tf
- infra/security_groups.tf
Replaced hardcoded SG rules with security_group_client_server_connections module for SageMaker, GitLab → ECR, and SentryProxy → internet.
Moved rule definitions to the client side.
Simplifies the code and reduces duplication.
Follows our updated convention for client-side SG rule ownership.
> Cleanup: Group SG

- infra/1010-gitlab--ecr.tf
This removes GitLab's security-group level access to ECR. Note that this removes access from the service itself (i.e. from inside the running Docker container), and not the EC2 instance that pulls the Docker image from ECR.
This is a belt-and-braces/swiss cheese change - doesn't close an actual known security vulnerability for several reasons, but since GitLab shouldn't be able to communicate with ECR, removing the security group rules that allows it to.
> security: remove GitLab ECS service access to ECR

- infra/0202-core--vpc-endpoints.tf
This tightens up the policy on the ECS endpoint
This makes sure that it can only be used by users/roles in our account.
> security: tighten up policy on ECS endpoint

- infra/modules/security_group_client_server_connections/main.tf
This changes the variables that the _keys_ for for_each in security_group_client_server_connections that security group rules are made from. Specifically, it uses the names of security groups rather than IDs.
While this less robust, since it can result in security group rules being (very briefly) dropped and re-created if a security group is renamed, without this you can get the error if applying the Terraform where the security groups have not yet been created:
> The "for_each" map includes keys derived from resource attributes that cannot be determined until apply, and so Terraform cannot determine the full set of keys that will identify the instances of this resource.
Since names are always hard-coded and so known before apply, this change avoids such errors.
An alternative to this …
> fix: use name rather than ID of security group in rule for_each

- infra/1003-gitlab--lb.tf
This reduces the deregistration delay for GitLab's target groups from the default 5 minutes to 5 seconds.
This is to reduce the time it takes to deploy a new GitLab. This is all acceptable from a user point of view because the deregistration delay is only applicable when a GitLab instance is shutting down and in our setup this means downtime anyway.
> infra: reduce gitlab deregistration delay

- infra/0101-variables.tf
- infra/1011-gitlab--ecs.tf
This adds a variable, gitlab_tag, so the GitLab Docker tag can be set per environment.
This is make it easier to test/deploy different versions of GitLab in different environments at the same time (and hopefully revert changes if necessary).
> feat: GitLab Docker tag set per environment

- infra/1007-gitlab--elasticache.tf
This increases the from of GitLab Redis from 5.0.6 to 7.1, and sets changes to be applied immediately.
This is because GitLab 16 seems to require a version of Redis >= 6, and applies immediately because that is what we want/expect, to not have to wait until a maintenance window.
> infra: increase the version of GitLab Redis

- infra/1007-gitlab--elasticache.tf
This corrects the parameter group for Redis 7
Otherwise terraform will not apply properly.
> fix: correct parameter group for Redis 7

- infra/1011-gitlab--ecs.tf
This disables the object storage for GitLab uploads
The bucket is empty - it was never actually functional. However, having it enabled now appears to break forks of projects with avatars. Forking such projects results in an error mentioning that the bucket "uploads.<bucket name>" does not exist. This is right, the bucket is just <bucket name>, so it's odd (maybe a bug with GitLab?)
> infra: disable (non functional) GitLab upload object storage

- infra/1010-gitlab--ecr.tf
This changes the GitLab ECR lifecycle policy to expire all but the most recently pushed image.
This is the best we can come up with given the constraints of the ECR lifecycle system. For example, we would base things on pull or push date, or make sure to keep images that are running, but these are not possible.
> infra: GitLab ECR lifecycle policy
