uktrade/data-workspace

README.md
This adds what is currently almost a straight copy of the README at https://github.com/uktrade/data-workspace-frontend
This is since this repo is to now be the main entry point for Data Workspace
=> docs: slightly fleshed out README

infra/ecr.tf, infra/ecs_main_gitlab.tf, infra/main.tf, infra/route_53.tf, infra/s3_gitlab.tf, infra/security_groups.tf
Setting `gitlab_on=false` will prevent the gitlab service and any related infrastructure from being started on an environment
=> feat: enable/disable gitlab based on `gitlab_on` var

README.md
In this particular case, because this is the entry-point, putting this much more up-front.
=> docs: put catalogue up front

docs/development.md
This slightly tidies up the development page. More specifically, is more accurately refers to the frontend repository, and it applies better highlighting onto blocks of shell commands.
=> docs: tidy up development page

docs/architecture.md, eleventy.config.js, package-lock.json, package.json
This uses a slightly lower level method of including Mermaid, and so it doesn't then conflict with syntax highlighting that comes from the Eleventy plugin used for GOV.UK styles.
=> docs: fix syntax highlighting

docs/sass/_settings.scss
The stronger blue is a bit better now I think
=> docs: use regular blue brand

docs/sass/_settings.scss
Think the softer is slightly better - gives it a bit more of an identity, and makes the logo stand out a bit more.
=> docs: go back to the less strong blue/green

infra/main.tf, infra/mwaa.tf
Mainly opting to not call it "dataflow" because that's fairly internal to DBT. Going for something more generic so at least in theory everything this repo can be used elsewhere.
Also making it so the bucket name is a variable that can be set - there is one namespace for all customers of AWS, so there is a chance of collision whatever we pick really.
=> feat: tidy up of MWAA names

infra/mwaa.tf
Not all envirnments will have MWAA, so to keep things tidy, making them all be dynamic (depending on the existance of mwaa_environment_name).
=> feat: allow all MWAA resources to be optional

infra/airflow_dag_tasks.tf, infra/airflow_scheduler.tf, infra/airflow_webserver.tf
So it's easier to manage/monitor them a little bit.
=> feat: separate cluster for Airflow DAG tasks

infra/airflow_dag_processor.tf, infra/airflow_dag_processor_container_definitions.json, infra/airflow_dag_tasks.tf, infra/airflow_dag_tasks_container_definitions.json, infra/airflow_scheduler.tf, infra/airflow_scheduler_container_definitions.json, infra/airflow_webserver.tf, infra/airflow_webserver_container_definitions.json, infra/main.tf, infra/security_groups.tf
Adding github dag sync to airflow dag processors
=> feat: ECS Airflow DAGs sync

package-lock.json
=> build(deps): bump various deps

infra/airflow_scheduler.tf
The reason being, scheduler currently uses the IAM roles from the webserver, this means that the websever has roles which it does not need. Therefore, adding in these IAM roles for shceduler directly will stop this issue.
=> feat: Adding in the IAM roles for scheduler

infra/airflow_webserver.tf, infra/airflow_webserver_container_definitions.json
We are adding in another webserver instance for high availability reasons and to surface any issues that we would get during deployments, we also noticed that the secret key details for the webserver was incorrect so we have changed that as well.
=> Feat: Adding in another webserver instance and fixing the secret key variable

infra/ecs_main_admin.tf, infra/ecs_main_admin_container_definitions.json, infra/main.tf
Doubling the amount of memory allocated to Celery, because it looked like it was running out of it on prod.
=> feat: increase memory on Celery

infra/main.tf
This PR sets default values for four ArangoDB related to empty string
=> Give default values for necessary ArangoDB variables

infra/ecs_notebooks.tf
To help diagnose visualisations issues (and maybe tools issues)
=> feat: enable container insights on notebooks cluster

infra/elasticsearch_datasets.tf
This role was used by dataset finder which is no longer used
=> Deleting elasticsearch role

infra/ecr.tf, infra/ecs_main_admin.tf, infra/ecs_main_admin_container_definitions.json, infra/ecs_main_gitlab.tf, infra/ecs_notebooks_vscode.tf
* vscode ecr
* vscode fargate spawner options
* vscode task definition
=> feat: terraform vscode

infra/sagemaker_model_example.tf
Adding autoscaling scheduling via cron
=> Autoscaling scheduling

infra/airflow_dag_processor.tf, infra/main.tf
What:
Added ability for dag processors and tasks to fetch from external buckets
Why:
To be able to fetch files from TAP bucket
=> Added ability for dag processors and tasks to fetch from external buckets

infra/sagemaker_llm_resources.tf
Updated to ensure longer time up and longer time to scale down for improving useability. Current testing shows this has improved use after initial cold-start.
=> Updated Alarm params

infra/ecs_main_gitlab.tf, infra/s3_notebooks.tf
add a policy change to allow data workspace users from vpce to get objects from notebooks S3 bucket
=> policy changes required for private package index for gitlab projects

infra/ecs_main_gitlab.tf
fixing resource format for gitlab data science runner
=> fixing resource format for gitlab ds runner

infra/modules/cloudwatch_alarm/sagemaker/main.tf, infra/modules/s3/main.tf, infra/modules/s3/outputs.tf, infra/modules/s3/variables.tf, infra/modules/sagemaker_deployment/main.tf, infra/modules/sagemaker_deployment/outputs.tf, infra/modules/sagemaker_deployment/variables.tf, infra/modules/sagemaker_init/iam/main.tf, infra/modules/sagemaker_init/iam/outputs.tf, infra/modules/sagemaker_init/iam/variables.tf, infra/modules/sns/main.tf, infra/modules/sns/outputs.tf, infra/modules/sns/variables.tf, infra/sagemaker.tf, infra/sagemaker_llm_resources.tf
Compliance, plus unfinished work on S3 bucket for logs - outstanding one more compliance metric but PR for now.
=> Compliance & alerting

infra/ecr.tf
applied to jupyterlab, theia, rv4-cran, rv4-rstudio, rv4-visualisation, pgadmin, remote-desktop, s3sync, and metrics.
=> applied to all tools

infra/ecs_notebooks_notebook.tf, infra/modules/sagemaker_deployment/main.tf, infra/modules/sagemaker_init/iam/main.tf, infra/sagemaker_llm_resources.tf, infra/vpc.tf
Undo some changes in an attempt to bring the state back closer to the last known working state
=> latest work to get back closer to last working state

infra/ecr.tf, infra/ecs_main_matchbox.tf, infra/security_groups.tf, infra/vpc.tf
Matchbox service added in main vpc with access to ECR.
=> Matchbox service connecting to ECR

infra/modules/sagemaker_deployment/lambda_function/sns_to_microsoft_teams.py, infra/modules/sagemaker_output_mover/lambda_function/s3_move_output.py
=> fix: address python linting errors

infra/ecs_notebooks_notebook.tf, infra/s3_notebooks.tf
=> remove non functional bugbear issues

infra/ecs_matchbox_matchbox.tf, infra/ecs_matchbox_matchbox_container_definitions.json, infra/environment-template/main.tf, infra/main.tf
add AWS Cloudwatch Subscription Filter for matchbox to send logs to ELK 
add new variable, Sentry DSN for matchbox to be included in container env var
=> add logging and monitoring to natchbox

infra/vpc.tf
The connection to SageMaker from notebooks is purely through the VPC endpoints  in the main VPC. There should not be any need for the notebooks to communicate with SageMaker using a mechanism other than these endpoints.
=> refactor: remove notebooks to SageMaker VPC peering connection

infra/security_groups.tf
Renaming some SageMaker security group rule names and descriptions to correctly signify
=> SageMaker security group rule names and description corrections

.github/pull_request_template.md
This PR adds a markdown template file that encourages helpful commit/PR messages to improve long-term maintainability
=> Copy PR template file from data-flow

infra/ecs_matchbox_matchbox.tf, infra/ecs_matchbox_matchbox_container_definitions.json, infra/main.tf
This adds a Datadog sidecar container to matchbox, very similar to how it was setup locally https://github.com/uktrade/matchbox/pull/87
=> feat: Matchbox/Datadog integration

infra/ecr.tf, infra/ecs_matchbox_matchbox.tf
This adds an ECR repo for Datadog.
Do the image can be pulled without communicating with DockerHub / the internet.
=> feat: in-house Datadog ECR repo

infra/ecs_matchbox_matchbox.tf
add environment prefix to matchbox IAM role
so that IAM role name is different between dev/staging/prod
=> add environment prefix to matchbox iam role

infra/main.tf, infra/security_groups.tf, infra/vpc.tf
This adds the ability for Airflow to pull from VPC resource endpoints. 
This is specifically useful to connect to other AWS Accounts (and specifically to allow connecting to RDS resources in other AWS accounts).
=> feat: ability to pull from VPC resource endpoints in Airflow

infra/modules/sagemaker_init/iam/main.tf
Introduce a 7 day retention policy on the S3 bucket that receives outputs from SageMaker inference endpoints.  
To improve data management practices.
=> feat: add retention policy to S3 bucket that contains SageMaker outputs

infra/ecr.tf, infra/ecs_main_admin.tf, infra/ecs_main_gitlab.tf, infra/ecs_tools.tf, infra/main.tf, infra/moved.tf, infra/security_groups.tf, infra/vscode_codebuild.tf
This moves almost all VS Code resource to an array, and specifically converts its CodeBuild-releated resources to a generic form.
What hasn't been done yet:
- Converting VS Code-related environment variables for the admin application to properly use the array
- Converting all the other on-demand tools, e.g. JupyterLab, RStudio etc, to use the array-based resources.
This is a stepping stone to configuring all on-demand tools using a single array, which should reduce duplication considerably and make it easier to fire up infrastructure per tool, and specifically fire up a CodeBuild project per tool.
=> refactor: move VS Code to generic array/count-based, especially for CodeBuild

infra/main.tf
This fixes the Remote Desktop build by using the correct Docker target name
=> fix: remove desktop build

infra/vscode_codebuild.tf
This PR adds both python and rv4 visualisation images to build in CodeBuild
Moving away from Jenkins
=> adding both python and rv4 visualisation images to build in CodeBuild

infra/0504-tools--codebuild.tf
This removes/combines unnecessary lists that only had one item each, and tidies up some indentation.
Part of ongoing work to tidy up the Terraform
=> refactor: remove unnecessary lists

infra/9802-legacy-tools-dns-rewrite-proxy--lb.tf, infra/ecs_main_dns_rewrite_proxy.tf
This removes the legacy/original DNS rewrite proxy
This is done since we have the "new" one (and have had it for some time)
=> infra: remove legacy DNS rewrite proxy

infra/startup.sh
This removes an unused script - suspect it was added when we were testing MWAA (Managed Workflows for Airflow)
This is part of work to tidy up the Terraform
=> refactor: remove unused script

infra/ecr.tf
This removes the ECR repo for rStudio R version 3
This is because it's unused - we've moved to R version 4
=> infra: remove used rStudio R version 3 ECR repo

infra/0618-tools-mirror-cran-binary--ecs.tf, infra/ecr.tf
This removes what are now unused ECR repositories that were used for mirroring. The repository for CRAN R version 4 mirror is left - that is still used.
This is done as a tidy up of the Terraform
=> infra: remove unused mirror ECR repositories

infra/0711-gitlab--ecs.tf
This removes templating from the GitLab omnibus config, and uses Terraform variables directly
Part of a wider tidy up of the Terraform
=> refactor: avoid unnecessary templating

infra/0610-tools-visualisations--ecr.tf, infra/ecr.tf
This moves the visualisation base repo definition to a numbered file
This is part of tidy up of the Terraform code
=> refactor: move visualisation base to numbered file

infra/0207-core-datadog--ecr.tf, infra/ecr.tf
This moves the definition for the datadog ECR repo to core. Although not yet, the rough plan is for it to be used in multiple services.
This is part of the ongoing tidy up of the Terraform
=> refactor: move datadog ecr to core

README.md, infra/README.md
This creates an initial version of the naming/grouping standards about where Terraform resources have to be placed.
More and more people are working on the Terraform, so having a consistent way avoids it getting _too_ spaghetti-like.
=> docs: initial Terraform standards

infra/modules/security_group_client_server_connections/main.tf
This adds a comment at the top of the security group module
This is so it's easier to understand/use/change
=> docs: add a comment at the top of the security group rule module

infra/modules/security_group_client_server_connections/main.tf
This tidies up and corrects the variable names in our security_group_client_server_connections module.
This is so it's easier to use/debug in future.
=> docs: tidy up and correct module variable descriptions

infra/1406-matchbox--ecs.tf, infra/1407-matchbox--codebuild.tf, infra/modules/codebuild_ecs_deploy/main.tf, infra/security_groups.tf
Refactor Matchbox CodeBuild to use our fairly new codebuild_ecs_deploy module. It includes a small fix to the module when using a non-default patch to the Dockerfile.
This is in keeping with the policy in infra/ to factor our modules, and in this case it keeps the amount of code/duplication down, especially around the boilerplate of creating a CodeBuild project.
=> refactor: matchbox codebuild to use codebuild module

infra/0301-frontend--rds.tf
always allow major version upgrade to postgres db engine
=> always allow major version upgrade to postgres db engine

infra/0101-variables.tf, infra/0905-tools--efs.tf, infra/0906-tools--ecs.tf
This initial version creates resources to mount EFS volume to all tools fargate containers, behind a feature flag. But eventually, we will have to create a folder per user and give exclusive permissions to read/write
This tidies up/removes some left over resources from a previous round of EFS experimentation that used access points. Suspect we will still use access points, but getting there in small steps tidying things up first, so we don't have anything left over we don't need.
This is a stepping stone on the way to using EFS to reduce dependency on the S3 syncing process, which has severe performance and stability issues in tools.
=>  feat: mount EFS volume in tools fargate container

infra/0811-airflow-team-dag-processor--ecs.tf
The previous change incorrectly assumed that airflow dag processor service was an array so it attempted to index into it but it didn't work.
=> fix: definition of matchbox security group rules

infra/1011-gitlab--ecs.tf
change pre-receive hook config to `gitaly['configuration']`, as it is changed from 16 onwards.
=> change pre-receive hook config, as it is changed from 16 onwards

infra/1011-gitlab--ecs.tf
This PR fixes ECS task definitions and disable all usage of S3 buckets for storing Gitlab artifacts etc
=> update and fix gitlab ECS task definition

infra/0301-frontend--rds.tf
This adds engine_version to the list of fields that Terraform should ignore on the admin database.
This is since it is upgraded either automatically, or through the Console (and it is also impossible to go _down_ a version)
=> chore: ignore admin database engine version changes
